/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames_internos;

import Interface.Modulos;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class frm_facturacion extends javax.swing.JInternalFrame implements Modulos {

    boolean datos_completos = false;
    double cantidad=0;

    public frm_facturacion(double c) {
        initComponents();
        this.setSize(605, 444);
        this.setTitle("Pagos y verificacion");
        this.cantidad=c;        
        this.txf_cantidad.setText(String.valueOf(c));
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        TextoPago = new javax.swing.JLabel();
        TextoIdTrans = new javax.swing.JLabel();
        TextoCantidConf = new javax.swing.JLabel();
        txf_cantidad = new javax.swing.JTextField();
        txf_id = new javax.swing.JTextField();
        box_pago = new javax.swing.JComboBox<>();
        btn_enviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 70, 600, 20);

        TextoPago.setText("Pago");
        getContentPane().add(TextoPago);
        TextoPago.setBounds(60, 100, 120, 35);

        TextoIdTrans.setText("ID de Transaccion");
        getContentPane().add(TextoIdTrans);
        TextoIdTrans.setBounds(60, 180, 230, 35);

        TextoCantidConf.setText("Confirmar Cantidad($)");
        getContentPane().add(TextoCantidConf);
        TextoCantidConf.setBounds(60, 260, 200, 35);

        txf_cantidad.setEditable(false);
        getContentPane().add(txf_cantidad);
        txf_cantidad.setBounds(60, 300, 470, 30);

        txf_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txf_idKeyTyped(evt);
            }
        });
        getContentPane().add(txf_id);
        txf_id.setBounds(60, 220, 470, 30);

        box_pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Paypal", "Tarjeta de Credito/Debito", "Efectivo" }));
        getContentPane().add(box_pago);
        box_pago.setBounds(60, 140, 470, 20);

        btn_enviar.setBackground(new java.awt.Color(0, 153, 0));
        btn_enviar.setForeground(new java.awt.Color(255, 255, 255));
        btn_enviar.setText("Proceder");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enviar);
        btn_enviar.setBounds(230, 360, 112, 43);

        jLabel1.setText("Ingrese detalles de pago para continuar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 40, 250, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        
        String id=txf_id.getText();
        String cantidad=txf_cantidad.getText();
        String tipo_pago=box_pago.getSelectedItem().toString();
        
        if (!id.equals("") && !tipo_pago.equals("Seleccionar")) {
            datos_completos = true;
            JOptionPane.showMessageDialog(null,"Datos ingresados correctamente");
        }else {
            JOptionPane.showMessageDialog(null, "Complete todos los datos","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void txf_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txf_idKeyTyped
        char F=evt.getKeyChar();
        
        if(Character.isLetter(F)){
            getToolkit();
            evt.consume();
            
            //JOptionPane.showMessageDialog(rootPane,"Texto");
        }
    }//GEN-LAST:event_txf_idKeyTyped

    public void setCantidad(double c){
    
        String cc=String.valueOf(c);
        this.txf_cantidad.setText(cc);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoCantidConf;
    private javax.swing.JLabel TextoIdTrans;
    private javax.swing.JLabel TextoPago;
    public javax.swing.JComboBox<String> box_pago;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField txf_cantidad;
    public javax.swing.JTextField txf_id;
    // End of variables declaration//GEN-END:variables

    public boolean esta_completo() {
        return datos_completos;
    }
}
