/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames_internos;

import Interface.Modulos;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class frm_contacto extends javax.swing.JInternalFrame implements Modulos {

    boolean datos_completos = false;

    public frm_contacto() {
        initComponents();
        this.setSize(605, 444);
        this.setTitle("Informacion de Contacto");
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoNombres = new javax.swing.JLabel();
        TextoEmail = new javax.swing.JLabel();
        TextoGenero = new javax.swing.JLabel();
        txf_email = new javax.swing.JTextField();
        txf_nombres = new javax.swing.JTextField();
        box_genero = new javax.swing.JComboBox<>();
        btn_enviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TextoNombres1 = new javax.swing.JLabel();
        txf_dni = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        TextoNombres.setText("Nombres");
        getContentPane().add(TextoNombres);
        TextoNombres.setBounds(60, 80, 60, 22);

        TextoEmail.setText("Email");
        getContentPane().add(TextoEmail);
        TextoEmail.setBounds(60, 220, 60, 22);

        TextoGenero.setText("Genero");
        getContentPane().add(TextoGenero);
        TextoGenero.setBounds(60, 290, 60, 22);
        getContentPane().add(txf_email);
        txf_email.setBounds(60, 250, 490, 28);

        txf_nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txf_nombresKeyTyped(evt);
            }
        });
        getContentPane().add(txf_nombres);
        txf_nombres.setBounds(60, 110, 490, 28);

        box_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Masculino", "Femenino" }));
        getContentPane().add(box_genero);
        box_genero.setBounds(60, 320, 200, 20);

        btn_enviar.setBackground(new java.awt.Color(0, 153, 0));
        btn_enviar.setForeground(new java.awt.Color(255, 255, 255));
        btn_enviar.setText("Enviar detalles");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enviar);
        btn_enviar.setBounds(240, 360, 140, 43);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Complete los campos requeridos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 40, 185, 16);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 70, 610, 2);

        TextoNombres1.setText("Dni");
        getContentPane().add(TextoNombres1);
        TextoNombres1.setBounds(60, 150, 50, 22);

        txf_dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txf_dniKeyTyped(evt);
            }
        });
        getContentPane().add(txf_dni);
        txf_dni.setBounds(60, 180, 200, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed

        String nombre = txf_nombres.getText();
        String dni = txf_dni.getText();
        String email = txf_email.getText();
        String genero = box_genero.getSelectedItem().toString();

        if (!nombre.equals("") && !dni.equals("") && !email.equals("") && !genero.equals("Seleccionar")) {
            
            datos_completos = true;            
            JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");
                
        } else {
            JOptionPane.showMessageDialog(null, "Complete todos los datos","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void txf_nombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txf_nombresKeyTyped
        char F=evt.getKeyChar();
        
        if(Character.isDigit(F)){
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_txf_nombresKeyTyped

    private void txf_dniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txf_dniKeyTyped
        char F=evt.getKeyChar();
        
        if(Character.isLetter(F) || txf_dni.getText().length()>=8){
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_txf_dniKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoEmail;
    private javax.swing.JLabel TextoGenero;
    private javax.swing.JLabel TextoNombres;
    private javax.swing.JLabel TextoNombres1;
    public javax.swing.JComboBox<String> box_genero;
    public javax.swing.JButton btn_enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField txf_dni;
    public javax.swing.JTextField txf_email;
    public javax.swing.JTextField txf_nombres;
    // End of variables declaration//GEN-END:variables

    public boolean esta_completo() {
        return datos_completos;
    }
}
