/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames_internos;

import Interface.Modulos;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class frm_detalles extends javax.swing.JInternalFrame implements Modulos {

    public boolean datos_completos = false;

    public frm_detalles() {
        initComponents();
        this.setSize(605, 444);
        this.setTitle("Informacion de Viaje y reserva");
        spiner_año.setValue(2020);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        box_clase = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btn_enviar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        box_destino = new javax.swing.JComboBox<>();
        spiner_asientos = new javax.swing.JSpinner();
        spiner_año = new javax.swing.JSpinner();
        spiner_dia = new javax.swing.JSpinner();
        spiner_mes = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setText("Año");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 280, 30, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Informacion de Reserva");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 10, 190, 30);

        jLabel3.setText("Reserva Nro: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 30, 150, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Asegurese de que todos los detalles se hayan llenado correctamente");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 330, 390, 30);

        jLabel5.setText("Destino");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 110, 250, 30);

        jLabel6.setText("Clase de Viaje");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 180, 250, 30);

        jLabel7.setText("Nro de Asientos");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 250, 140, 30);

        box_clase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Turista", "Turista Superior", "Primera Clase", "Ejecutivo VIP" }));
        getContentPane().add(box_clase);
        box_clase.setBounds(80, 210, 470, 26);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Ingrese informacion de reserva de viaje");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 60, 250, 30);

        btn_enviar.setBackground(new java.awt.Color(0, 153, 0));
        btn_enviar.setForeground(new java.awt.Color(255, 255, 255));
        btn_enviar.setText("Enviar detalles");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enviar);
        btn_enviar.setBounds(240, 360, 120, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 92, 610, 10);

        box_destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "De Lima a Cuzco", "De Lima a Trujillo", "De Lima a Jauja", "De Lima a Ayacucho", "De Lima a Arequipa", "De Lima a Iquitos", "De Lima a Cajamarca", "De Lima a Huanuco", "De Lima a Tingo Maria", "De Lima a Pisco", "De Lima a Piura", "De Lima a Tacna", "De Lima a Pucallpa", "De Lima a Tumbes", "De Jauja a Lima", "De Jauja a Cuzco", "De Jauja a Trujillo", "De Jauja a Yungay", "De Jauja a Ayacucho", "De Jauja a Arequipa", "De Jauja a Iquitos", "De Jauja a Cajamarca", "De Jauja a Huanuco", "De Jauja a Tingo Maria", "De Jauja a Pisco", "De Jauja a Piura", "De Jauja a Tacna", "De Jauja a Pucallpa", "De Jauja a Tumbes" }));
        getContentPane().add(box_destino);
        box_destino.setBounds(80, 140, 470, 26);

        spiner_asientos.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(spiner_asientos);
        spiner_asientos.setBounds(80, 280, 180, 26);

        spiner_año.setModel(new javax.swing.SpinnerNumberModel(2021, 2020, 3000, 1));
        getContentPane().add(spiner_año);
        spiner_año.setBounds(480, 280, 70, 26);

        spiner_dia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        getContentPane().add(spiner_dia);
        spiner_dia.setBounds(300, 280, 50, 26);

        spiner_mes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        getContentPane().add(spiner_mes);
        spiner_mes.setBounds(390, 280, 50, 26);

        jLabel9.setText("Fecha de Viaje");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 250, 140, 30);

        jLabel10.setText("Dia");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(280, 280, 30, 30);

        jLabel11.setText("Mes");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(360, 280, 30, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean esta_completo() {
        return datos_completos;
    }

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed

        String destino = box_destino.getSelectedItem().toString();
        String clase = box_clase.getSelectedItem().toString();
        int n_asientos = (int) spiner_asientos.getValue();
        int dia =(int) spiner_dia.getValue();
        int mes=(int) spiner_mes.getValue();
        int ano=(int) spiner_año.getValue();

        if (!destino.equals("Seleccionar") && !clase.equals("Seleccionar") && n_asientos != 0 && dia != 0 && mes != 0 && ano != 0) {

            datos_completos = true;
            JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");

        } else {
            JOptionPane.showMessageDialog(null, "Complete todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_enviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> box_clase;
    public javax.swing.JComboBox<String> box_destino;
    public javax.swing.JButton btn_enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JSpinner spiner_asientos;
    public javax.swing.JSpinner spiner_año;
    public javax.swing.JSpinner spiner_dia;
    public javax.swing.JSpinner spiner_mes;
    // End of variables declaration//GEN-END:variables
}
