/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventas;

import Datos.p_cliente;
import Datos.p_detalle_reserva;
import Datos.p_fecha;
import Datos.p_pago;
import Datos.p_reserva;
import frames_internos.frm_confirmacion;
import frames_internos.frm_facturacion;
import frames_internos.frm_contacto;
import frames_internos.frm_finalizacion;
import frames_internos.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Jose
 */
public class Interfaz extends javax.swing.JFrame {

    frm_detalles f_detalles;
    frm_contacto f_contacto;
    frm_confirmacion f_confirmacion;
    frm_facturacion f_facturacion;
    frm_finalizacion f_finalizacion;

    p_reserva reserva;

    public Interfaz() {
        initComponents();

        this.setTitle("Sistema de reservas de tickets aereos");
        this.setSize(800, 500);

        btn_detalles.setVisible(false);
        btn_contacto.setVisible(false);
        btn_facturacion.setVisible(false);
        btn_confirmar.setVisible(false);
        btn_terminar.setVisible(false);
        btn_siguiente.setVisible(false);
        escritorio.setVisible(false);

        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/ico_avion.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btn_terminar = new javax.swing.JButton();
        btn_detalles = new javax.swing.JButton();
        btn_contacto = new javax.swing.JButton();
        btn_facturacion = new javax.swing.JButton();
        btn_confirmar = new javax.swing.JButton();
        btn_reservar = new javax.swing.JButton();
        btn_administrador = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Sistema de Reservas de Tickets Aereos");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 31);

        btn_terminar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_terminar.setText("Terminar e Imprimir");
        btn_terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_terminar);
        btn_terminar.setBounds(10, 350, 160, 40);

        btn_detalles.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_detalles.setText("Detalles de Reserva");
        btn_detalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detallesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_detalles);
        btn_detalles.setBounds(10, 150, 160, 40);

        btn_contacto.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_contacto.setText("Informacion Contacto");
        btn_contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contactoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_contacto);
        btn_contacto.setBounds(10, 200, 160, 40);

        btn_facturacion.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_facturacion.setText("Facturación");
        btn_facturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facturacionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_facturacion);
        btn_facturacion.setBounds(10, 250, 160, 40);

        btn_confirmar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_confirmar.setText("Confirmar Detalles");
        btn_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_confirmar);
        btn_confirmar.setBounds(10, 300, 160, 40);

        btn_reservar.setBackground(new java.awt.Color(0, 174, 12));
        btn_reservar.setForeground(new java.awt.Color(255, 255, 255));
        btn_reservar.setText("¡Reservar!");
        btn_reservar.setPreferredSize(new java.awt.Dimension(80, 30));
        btn_reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reservarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reservar);
        btn_reservar.setBounds(320, 200, 169, 56);

        btn_administrador.setBackground(new java.awt.Color(255, 70, 59));
        btn_administrador.setForeground(new java.awt.Color(255, 255, 255));
        btn_administrador.setText("Acceso Administrador");
        btn_administrador.setPreferredSize(new java.awt.Dimension(80, 30));
        btn_administrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_administradorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_administrador);
        btn_administrador.setBounds(320, 270, 168, 41);

        btn_siguiente.setBackground(new java.awt.Color(0, 51, 102));
        btn_siguiente.setForeground(new java.awt.Color(255, 255, 255));
        btn_siguiente.setText("Siguiente");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_siguiente);
        btn_siguiente.setBounds(90, 420, 83, 32);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio);
        escritorio.setBounds(190, 30, 605, 444);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wall_avion.jpg"))); // NOI18N
        jLabel2.setText("gg");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 30, 800, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservarActionPerformed
        btn_detalles.setVisible(true);
        btn_detalles.setEnabled(true);
        btn_contacto.setVisible(true);
        btn_contacto.setEnabled(false);
        btn_facturacion.setVisible(true);
        btn_facturacion.setEnabled(false);
        btn_confirmar.setVisible(true);
        btn_confirmar.setEnabled(false);
        btn_terminar.setVisible(true);
        btn_terminar.setEnabled(false);
        escritorio.setVisible(true);
        btn_reservar.setVisible(false);
        btn_administrador.setVisible(false);
        btn_siguiente.setVisible(true);
        btn_siguiente.setText("Siguiente");
    }//GEN-LAST:event_btn_reservarActionPerformed

    public void mostrar_detalles() {
        if (f_detalles == null) {
            f_detalles = new frm_detalles();
            escritorio.add(f_detalles);
            escritorio.getDesktopManager().maximizeFrame(f_detalles);
            f_detalles.setVisible(true);
            pos_boton = 1;

        } else {
            escritorio.getDesktopManager().maximizeFrame(f_detalles);
        }
    }

    public void mostrar_contacto() {
        if (f_contacto == null) {
            f_contacto = new frm_contacto();
            escritorio.add(f_contacto);
            escritorio.getDesktopManager().maximizeFrame(f_contacto);
            f_contacto.setVisible(true);
            pos_boton = 2;

        } else {
            escritorio.getDesktopManager().maximizeFrame(f_contacto);
        }
    }

    public void mostrar_facturacion() {
        if (f_facturacion == null) {
            f_facturacion = new frm_facturacion(asignar_cantidad());
            escritorio.add(f_facturacion);
            escritorio.getDesktopManager().maximizeFrame(f_facturacion);
            f_facturacion.setVisible(true);
            pos_boton = 3;

        } else {
            f_facturacion.setCantidad(asignar_cantidad());
            escritorio.getDesktopManager().maximizeFrame(f_facturacion);
        }
    }

    public void mostrar_confirmar() {
        if (f_confirmacion == null) {
            recoger_datos();
            f_confirmacion = new frm_confirmacion(reserva);
            escritorio.add(f_confirmacion);
            escritorio.getDesktopManager().maximizeFrame(f_confirmacion);
            f_confirmacion.setVisible(true);
            pos_boton = 4;
        } else {
            f_confirmacion.dispose();
            recoger_datos();
            f_confirmacion = new frm_confirmacion(reserva);
            escritorio.add(f_confirmacion);
            escritorio.getDesktopManager().maximizeFrame(f_confirmacion);
            f_confirmacion.setVisible(true);
            pos_boton = 4;
        }
    }

    public void mostrar_terminar() {
        if (f_finalizacion == null) {
            recoger_datos();
            f_finalizacion = new frm_finalizacion(reserva);
            escritorio.add(f_finalizacion);
            escritorio.getDesktopManager().maximizeFrame(f_finalizacion);
            f_finalizacion.setVisible(true);
            pos_boton = 5;
            btn_detalles.setEnabled(false);
            btn_contacto.setEnabled(false);
            btn_facturacion.setEnabled(false);
            btn_confirmar.setEnabled(false);
            btn_siguiente.setText("Finalizar");

            escritorio.getDesktopManager().closeFrame(f_detalles);
            escritorio.getDesktopManager().closeFrame(f_contacto);
            escritorio.getDesktopManager().closeFrame(f_facturacion);
            escritorio.getDesktopManager().closeFrame(f_confirmacion);

        } else {
            escritorio.getDesktopManager().maximizeFrame(f_finalizacion);
        }
    }

    private void btn_detallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detallesActionPerformed
        mostrar_detalles();
    }//GEN-LAST:event_btn_detallesActionPerformed

    private void btn_contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contactoActionPerformed
        mostrar_contacto();
    }//GEN-LAST:event_btn_contactoActionPerformed

    private void btn_facturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facturacionActionPerformed
        mostrar_facturacion();
    }//GEN-LAST:event_btn_facturacionActionPerformed

    private void btn_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmarActionPerformed
        mostrar_confirmar();
    }//GEN-LAST:event_btn_confirmarActionPerformed

    private void btn_terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terminarActionPerformed
        mostrar_terminar();
    }//GEN-LAST:event_btn_terminarActionPerformed

    int pos_boton = 0;
    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        try {
            if (btn_siguiente.getText().equals("Finalizar")) {
                btn_detalles.setVisible(false);
                btn_contacto.setVisible(false);
                btn_facturacion.setVisible(false);
                btn_confirmar.setVisible(false);
                btn_terminar.setVisible(false);
                escritorio.getDesktopManager().closeFrame(f_finalizacion);
                escritorio.setVisible(false);
                btn_reservar.setVisible(true);
                btn_administrador.setVisible(true);
                btn_siguiente.setVisible(false);
                vaciar_frames();
            }
            if (f_detalles.esta_completo() && pos_boton == 1) {
                btn_contacto.setEnabled(true);
                mostrar_contacto();
            }
            if (f_contacto.esta_completo() && pos_boton == 2) {
                btn_facturacion.setEnabled(true);
                mostrar_facturacion();
            }
            if (f_facturacion.esta_completo() && pos_boton == 3) {
                btn_confirmar.setEnabled(true);
                mostrar_confirmar();
            }
            if (f_confirmacion.esta_completo() && pos_boton == 4) {
                btn_terminar.setEnabled(true);
                mostrar_terminar();
            }
            if (f_finalizacion.esta_completo() && pos_boton == 5) {
                btn_siguiente.setEnabled(false);
                
            }
            
        } catch (Exception e) {
            e.getMessage();
        }

    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void btn_administradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_administradorActionPerformed
      Tickets t=new Tickets();
      t.setVisible(true);
    }//GEN-LAST:event_btn_administradorActionPerformed

    public void vaciar_frames() {
        f_detalles = null;
        f_contacto = null;
        f_confirmacion = null;
        f_facturacion = null;
        f_finalizacion = null;
    }

    public void recoger_datos() {

        String destino = f_detalles.box_destino.getSelectedItem().toString();
        String clase = f_detalles.box_clase.getSelectedItem().toString();
        int n_asientos = (int) f_detalles.spiner_asientos.getValue();
        int dia = (int) f_detalles.spiner_dia.getValue();
        int mes = (int) f_detalles.spiner_mes.getValue();
        int ano = (int) f_detalles.spiner_año.getValue();

        String nombre = f_contacto.txf_nombres.getText();
        String dni = f_contacto.txf_dni.getText();
        String email = f_contacto.txf_email.getText();
        String genero = f_contacto.box_genero.getSelectedItem().toString();

        String id = f_facturacion.txf_id.getText();
        String cantidad_pago = f_facturacion.txf_cantidad.getText();
        String tipo_pago = f_facturacion.box_pago.getSelectedItem().toString();

        p_cliente cliente = new p_cliente();
        p_fecha fecha = new p_fecha();
        p_detalle_reserva det_reserva = new p_detalle_reserva();
        p_pago pago = new p_pago();

        cliente.setNombre(nombre);
        cliente.setDni(dni);
        cliente.setEmail(email);
        cliente.setGenero(genero);

        fecha.setDia(dia);
        fecha.setMes(mes);
        fecha.setAno(ano);

        det_reserva.setAsientos(n_asientos);
        det_reserva.setClase(clase);
        det_reserva.setDestino(destino);

        pago.setId_transaccion(id);
        pago.setTipo_pago(tipo_pago);
        pago.setCant_pago(cantidad_pago);

        this.reserva = new p_reserva();
        reserva.setCliente(cliente);
        reserva.setPago(pago);
        reserva.setDetalle_reserva(det_reserva);
        reserva.setFecha(fecha);
    }

    double cantidad = 0;

    public double asignar_cantidad() {

        String clase = f_detalles.box_clase.getSelectedItem().toString();
        int n_asientos = (Integer) f_detalles.spiner_asientos.getValue();

        
        if (clase.equalsIgnoreCase("Turista")) {
            cantidad = n_asientos * 124; //precio de turista es 100 soles
        }
        if (clase.equalsIgnoreCase("Turista Superior")) {
            cantidad = n_asientos * 224; //precio 200
        }
        if (clase.equalsIgnoreCase("Primera Clase")) {
            cantidad = n_asientos * 524; //precio 500
        }
        if (clase.equalsIgnoreCase("Ejecutivo VIP")) {
            cantidad = n_asientos * 1024; //precio 1000
        }

        return cantidad;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_administrador;
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JButton btn_contacto;
    public javax.swing.JButton btn_detalles;
    private javax.swing.JButton btn_facturacion;
    private javax.swing.JButton btn_reservar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JButton btn_terminar;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
