/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ohpan
 */
public class main_login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public main_login() {
        initComponents();
        this.setSize(400, 330);
        this.setTitle("Iniciar Sesion");
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/ico_avion.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Perfil = new javax.swing.JLabel();
        TextoUsuario = new javax.swing.JLabel();
        TextoPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        TxTUser = new javax.swing.JTextField();
        TxTPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas(Login)");
        setResizable(false);
        getContentPane().setLayout(null);

        Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LoginPerfil.png"))); // NOI18N
        getContentPane().add(Perfil);
        Perfil.setBounds(150, 30, 90, 90);

        TextoUsuario.setText("Usuario");
        getContentPane().add(TextoUsuario);
        TextoUsuario.setBounds(80, 130, 44, 16);

        TextoPassword.setText("Contraseña");
        getContentPane().add(TextoPassword);
        TextoPassword.setBounds(80, 180, 66, 16);

        btnLogin.setText("Iniciar Sesion");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(130, 240, 120, 32);
        getContentPane().add(TxTUser);
        TxTUser.setBounds(80, 150, 220, 24);
        getContentPane().add(TxTPass);
        TxTPass.setBounds(80, 200, 220, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ii.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 402, 311);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String usuario = TxTUser.getText();
        String contraseña = TxTPass.getText();
        if(usuario.equals("admin") && contraseña.equals("admin")){
              Interfaz i=new Interfaz();
              i.setVisible(true);
              this.dispose();

        }else{
            JOptionPane.showMessageDialog(null, "Los datos que ingreso son incorrectos");
            TxTUser.setText("");
            TxTPass.setText("");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Perfil;
    private javax.swing.JLabel TextoPassword;
    private javax.swing.JLabel TextoUsuario;
    private javax.swing.JPasswordField TxTPass;
    private javax.swing.JTextField TxTUser;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
